[package]
name = "atom"
version = "0.4.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/slide-rs/atom"
description = "A safe abstraction around AtomicPtr"
